# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/23906eb2-26ee-4a19-9a63-48d9f83b937b";
    fsType = "ext4";
  };

  fileSystems."/mnt/mint" = {
    device = "/dev/disk/by-uuid/81503bb0-48b0-486a-8890-266628de3419";
    fsType = "btrfs";
  };

  fileSystems."/mnt/win" = {
    device = "/dev/disk/by-uuid/66E2FB4FE2FB224B";
    fsType = "ntfs";
  };

  fileSystems."/mnt/shit" = {
    device = "/dev/disk/by-uuid/DCFE4455FE4429DA";
    fsType = "ntfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-partuuid/42fea704-ae86-4a29-905c-4bc7eaa62da0";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/gaming/fast" = {
    device = "/dev/disk/by-partuuid/9de2fd24-e057-473d-8f66-be0740a15a79";
    fsType = "ext4";
  };

  fileSystems."/gaming/slow" = {
    device = "/dev/disk/by-partuuid/878e9a01-a640-440a-952c-7b343c76fddf";
    fsType = "ext4";
  };

  fileSystems."/server" = {
    device = "botserver@192.168.50.82:/home/botserver";
    fsType = "sshfs";
    options = [
      "nodev"
      "noatime"
      "allow_other"
      "IdentityFile=/root/.ssh/id_ed25519"
    ];
  };


  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/5cf85b3a-ea07-47a3-a0f7-0c3cb939467b";
      # randomEncryption.enable = true;
    }
    {
      device = "/dev/nvme1n1p1";
    }
    {
      device = "/dev/sdc2";
    }
    {
      device = "/dev/sdd1";
    }
    # {
    #   device = "/swapfile";
    #   size = 64 * 1024;
    # }
  ];
  zramSwap.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
